name: Install SonarQube scanner
description: A GitHub Action to install sonarscanner with java, in a platform agnostic way
author: NOS Inovação
branding:
  color: blue
  icon: search

inputs:
  version:
    description: The version of the scanner to be used
    required: false
    default: 6.1.0.4477
  javaDistribution:
    description: The distribution of Java to be used
    required: false
    default: 'temurin'
  javaVersion:
    description: The version of Java to be used
    required: false
    default: '21' # Latest LTS version

runs:
  using: composite
  steps:

    - name: Check if java is installed
      shell: bash
      continue-on-error: false
      id: check-java
      run: |
        if command -v java; then
          echo "Java is installed"
          echo "javaInstalled=true" >> $GITHUB_OUTPUT
        else
          echo "Java is not installed"
          echo "javaInstalled=false" >> $GITHUB_OUTPUT
        fi

    # Installs Java if requested by the user
    - name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # pin @v4.2.1
      if: steps.check-java.outputs.javaInstalled == 'false'
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}

    - name: Set up SonarQube scanner
      shell: bash
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ inputs.version }}.zip -O /tmp/sonar-scanner.zip
        unzip /tmp/sonar-scanner.zip -d /tmp
        echo "/tmp/sonar-scanner-${{ inputs.version }}/bin" >> $GITHUB_PATH